export const sideNavStyles = {
    container: {
        backgroundColor: "transparent",
        marginBottom: "0",
        left: "0px",
        transform: "translateX(0px)",
        transition: "width 225ms cubic-bezier(0.4, 0, 0.6, 1) 0ms, background-color 225ms cubic-bezier(0.4, 0, 0.6, 1) 0ms",
        border: "none",
        boxShadow: "none",
        color: "rgba(0, 0, 0, 0.87)",
        overflow: "unset",
        display: "flex",
        flexDirection: "column",
        flex: "1 0 auto",
        zIndex: 1200,
        position: "fixed",
        top: "0px",
        outline: "0px",
        backdropFilter: "saturate(200%) blur(1.875rem)",
        height: "calc(100vh - 2rem)",
        margin: "1rem",
        borderRadius: "1rem",
        padding: "0px",
        overflowY: "auto"

    },
    smallContainer: {
        transform: "translateX(0px)",
        transition: "transform 200ms cubic-bezier(0.4, 0, 0.6, 1) 0ms",
        boxShadow: "rgb(0 0 0 / 5%) 0rem 1.25rem 1.6875rem 0rem",
        border: "none",
        color: "rgba(0, 0, 0, 0.87)",
        overflow: "unset",
        display: "flex",
        flexDirection: "column",
        marginBottom: "0",
        flex: "1 0 auto",
        zIndex: 1200,
        position: "fixed",
        top: "0px",
        outline: "0px",
        left: "0px",
        backgroundColor: "transparent",
        backdropFilter: "saturate(200%) blur(1.875rem)",
        height: "calc(100vh - 2rem)",
        margin: "1rem",
        borderRadius: "1rem",
        padding: "0px",
        overflowY: "auto"
    },
}